### ISSUE TITLE
can not unlock Yubikey

### ISSUE THREAD

**Issue by freddyb** [bfelder/YubiLock#4]
I tried to debug this myself, but couldn't even figure out how the code works (threading and multi-process make this a tad confusing).

How and where does it listen on "Super Y"?
I'd like to change this to Meta+Y, possibly.

**Comment by pykong** [comment]
**You need to make a system shortcut to the script with -t as a parameter.**
Like so: _"/path/to/my/script/YubiGuard.py -t"_

You may use any key combination your system allows, if so even Meta + Y.

Here is a short explanation on how to change key bindings under Linux Mint:
https://www.lifewire.com/how-to-change-the-linux-mint-cinnamon-keyboard-shortcuts-4064754

I deliberately chose this way of triggering, instead of endowing YubiGuard with an own key listener.

Note also that YubiGuard does work with many, but not on all Linux distributions.
See Readme for further information. (Or just ask.)

**Comment by freddyb** [comment]
Oh, I thought it does that in itself and was super confused because I couldn't find it. My bad.

**Comment by pykong** [comment]
It might not be your fault. Maybe the Readme needs to be clearer... ;-)

If you have any additional questions regarding the YubiGuard, just feel free to ask.

**Comment by pykong** [comment]
Closed.
